feat: zwave-js@10.6.0 heal network options support and endpoints labels
zwave-js/zwave-js-ui pull request #2941
Opened 2023-02-03 13:51 UTC by robertsLando

Removed `endpointIndezes` in favor of `endpoint` property from ZUINode

2023-02-03 14:25 UTC, AlCalzone requested changes

2023-02-03 14:25 UTC, AlCalzone commented on src/views/ControlPanel.vue
> +										value: false,
Default is `true` in the driver for compatibility reasons. I guess default `false` here is okay.

2023-02-03 14:25 UTC, AlCalzone commented on src/components/nodes-table/AssociationGroups.vue
> +				return ep?.label ? ep.label : 'Endpoint ' + endpoint
```suggestion
				return ep?.label || 'Endpoint ' + endpoint
```

2023-02-03 14:26 UTC, AlCalzone commented on src/components/dialogs/DialogAssociation.vue
> +						text: endpoint.label || 'Endpoint ' + endpoint.index,
this is the actual change request, the other comments are just information/hints

2023-02-03 15:10 UTC, robertsLando commented on src/components/nodes-table/AssociationGroups.vue
> +				return ep?.label ? ep.label : 'Endpoint ' + endpoint
Yeah, didn't noticed this, even better:

```
if (node) {
				const ep = node.endpoints.find((e) => e.index === endpoint)
				if (ep) {
					return ep.label
				}
			}

			return 'Endpoint ' + endpoint
```

2023-02-03 15:11 UTC, robertsLando commented on src/components/dialogs/DialogAssociation.vue
> +						text: endpoint.label || 'Endpoint ' + endpoint.index,
I think we could do this on backend side directly, I mean set the label to that on root endoint and if not set

2023-02-06 11:40 UTC, AlCalzone approved these changes

2023-02-06 12:13 UTC, merged